### ISSUE TITLE
Deployment Epic: Automate Infrastructure and CI/CD Pipeline for Linkarooie

### ISSUE THREAD

**Issue by loftwah** [loftwah/linkarooie#17]
### Overview

We aim to transition our infrastructure to a fully automated, zero-downtime deployment pipeline using **Terraform**, **Docker**, **Traefik**, **GitHub Actions**, and **Cloudflare**. We'll set up a test environment using a separate domain to validate everything before replacing our production setup.

### Objectives

- **Automate infrastructure provisioning** with Terraform.
- **Configure Docker Compose** and Traefik for service orchestration and reverse proxy.
- **Set up a CI/CD pipeline** with GitHub Actions.
- **Optimize SQLite usage** by embedding it within the application container.
- **Automate DNS management** with Cloudflare.

### Deployment Plan

---

#### **Step 1: Automate Infrastructure with Terraform**

**Objective**: Use Terraform to provision a DigitalOcean droplet for the application, automate Docker installation, and set up basic networking.

**Instructions**:

1. **Prepare Terraform Configuration**

   - **Install Terraform**: Ensure Terraform is installed locally.
   - **Create Configuration Files**: Set up a directory for your Terraform files (`main.tf`, `variables.tf`, etc.).

2. **Define Provider and Variables**

   ```hcl
   # main.tf
   terraform {
     required_providers {
       digitalocean = {
         source  = "digitalocean/digitalocean"
         version = "~> 2.0"
       }
     }
   }

   provider "digitalocean" {
     token = var.do_token
   }

   variable "do_token" {
     description = "DigitalOcean API token"
   }

   variable "ssh_key_id" {
     description = "SSH key ID for DigitalOcean"
   }

   variable "region" {
     description = "DigitalOcean region"
     default     = "syd1"
   }
   ```

3. **Define Resources for Droplet**

   - Since SQLite is embedded, we only need one droplet for the application.

   ```hcl
   # main.tf continued
   resource "digitalocean_droplet" "app" {
     name       = "linkarooie-app"
     region     = var.region
     size       = "s-2vcpu-4gb"
     image      = "ubuntu-22-04-x64"
     ssh_keys   = [var.ssh_key_id]
     user_data  = file("cloud-init-app.sh")
   }

   output "app_droplet_ip" {
     value       = digitalocean_droplet.app.ipv4_address
     description = "IP address of the application droplet"
   }
   ```

4. **Create Cloud-Init Script for Droplet Setup**

   - **cloud-init-app.sh**:

     ```bash
     #!/bin/bash
     apt-get update -y
     curl -fsSL https://get.docker.com | sh
     ```

**Checkpoints**:

- **Terraform Initialization**: Run `terraform init` and `terraform plan` to ensure configurations are correct.

- **Apply Changes**: Execute `terraform apply -auto-approve` to create resources.

- **Verification**:

  - Droplet is created and visible in the DigitalOcean dashboard.
  - SSH access to the droplet is functional.
  - Docker is installed on the droplet (`docker --version`).

---

#### **Step 2: Configure Docker Compose and Traefik**

**Objective**: Set up Docker Compose to manage application services and Traefik as a reverse proxy for dynamic routing and SSL/TLS termination.

**Instructions**:

1. **Create Docker Compose Configuration**

   - **docker-compose.yml**:

     ```yaml
     services:
       traefik:
         image: traefik:v2.10
         command:
           - "--providers.docker=true"
           - "--entrypoints.web.address=:80"
           - "--entrypoints.websecure.address=:443"
           - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
           - "--certificatesresolvers.myresolver.acme.email=your-email@example.com"
           - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
         ports:
           - "80:80"
           - "443:443"
         volumes:
           - "/var/run/docker.sock:/var/run/docker.sock:ro"
           - "./letsencrypt:/letsencrypt"

       app:
         image: ghcr.io/yourusername/linkarooie:latest
         labels:
           - "traefik.enable=true"
           - "traefik.http.routers.app.rule=Host(`app.yourdomain.com`)"
           - "traefik.http.routers.app.entrypoints=websecure"
           - "traefik.http.routers.app.tls=true"
           - "traefik.http.routers.app.tls.certresolver=myresolver"
           - "traefik.http.services.app.loadbalancer.server.port=3000"
         environment:
           - RAILS_ENV=production
         volumes:
           - ./storage:/app/storage
           - ./db:/app/db # Persist SQLite database
     ```

   - **Notes**:

     - Removed unnecessary services (e.g., Redis, Sidekiq) if not used.
     - Ensured SQLite database is persisted via volume.

2. **Persist SQLite Database**

   - Use Docker volumes to persist the SQLite database:

     ```yaml
     volumes:
       db_data:
     ```

   - Update the `app` service to use the volume:

     ```yaml
     services:
       app:
         # ...
         volumes:
           - db_data:/app/db
     ```

**Checkpoints**:

- **Start Services**: Run `docker-compose up -d` on the application droplet.

- **Verify Containers**: Use `docker ps` to ensure all containers are running.

- **Test Application**:

  - Access the application via `https://app.yourdomain.com`.
  - Confirm that data persists between restarts due to the SQLite volume.

- **Traefik Configuration**:
  - Ensure Traefik is routing requests correctly and SSL certificates are issued.

---

#### **Step 3: Set Up CI/CD with GitHub Actions**

**Objective**: Automate the build, test, and deployment process using GitHub Actions.

**Instructions**:

1. **Create GitHub Actions Workflow**

   - **.github/workflows/deploy.yml**:

     ```yaml
     name: CI/CD Pipeline

     on:
       push:
         branches:
           - main

     jobs:
       build-and-deploy:
         runs-on: ubuntu-latest

         steps:
           - name: Checkout code
             uses: actions/checkout@v2

           - name: Set up Docker Buildx
             uses: docker/setup-buildx-action@v1

           - name: Login to GitHub Container Registry
             uses: docker/login-action@v1
             with:
               registry: ghcr.io
               username: ${{ github.actor }}
               password: ${{ secrets.GITHUB_TOKEN }}

           - name: Build and push Docker image
             run: |
               docker buildx build --platform linux/amd64 \
                 -t ghcr.io/yourusername/linkarooie:latest \
                 --push .

           - name: Deploy with Terraform
             uses: hashicorp/terraform-action@v2.0.0
             with:
               cli_config_credentials_token: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
             env:
               TF_VAR_do_token: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
               TF_VAR_ssh_key_id: ${{ secrets.SSH_KEY_ID }}
               TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
             run: |
               terraform init
               terraform apply -auto-approve
     ```

2. **Secure Secrets Management**

   - Store sensitive information like API tokens and SSH keys in GitHub Actions secrets.

**Checkpoints**:

- **Workflow Execution**:

  - Ensure the workflow triggers on pushes to the `main` branch.
  - Verify that Docker images are built and pushed to GitHub Container Registry.
  - Confirm Terraform applies infrastructure changes without errors.

- **Deployment Verification**:

  - Check that the latest changes are deployed to the droplet.
  - Validate that the application is running smoothly after deployment.

---

#### **Step 4: Automate DNS Management with Cloudflare**

**Objective**: Use Cloudflare API to automate DNS updates during deployments.

**Instructions**:

1. **Update Terraform Configuration**

   - **Add Cloudflare Provider**:

     ```hcl
     # main.tf
     provider "cloudflare" {
       api_token = var.cloudflare_api_token
     }

     variable "cloudflare_api_token" {
       description = "Cloudflare API token"
     }
     ```

   - **Manage DNS Records**:

     ```hcl
     resource "cloudflare_record" "app" {
       zone_id = var.cloudflare_zone_id
       name    = "app"
       value   = digitalocean_droplet.app.ipv4_address
       type    = "A"
       ttl     = 1
       proxied = true
     }

     variable "cloudflare_zone_id" {
       description = "Cloudflare Zone ID"
     }
     ```

2. **Apply Terraform Changes**

   - Run `terraform apply -auto-approve` to update DNS records.

**Checkpoints**:

- **DNS Records**:

  - Verify that the DNS records are updated in the Cloudflare dashboard.
  - Ensure that `app.yourdomain.com` resolves to the new droplet IP.

- **SSL Verification**:

  - Confirm that SSL certificates are issued and valid.
  - Access the application via HTTPS without security warnings.

---

#### **Final Validation and Cutover**

1. **Testing on a Separate Domain**

   - Use a subdomain like `test.yourdomain.com` for initial testing.
   - Update the Terraform configuration and Traefik labels accordingly.

2. **Validate All Components**

   - **Infrastructure**: Droplet provisioning and accessibility.
   - **Application**: Functionality and data persistence with SQLite.
   - **Routing and SSL**: Traefik correctly routes traffic and handles SSL termination.
   - **CI/CD Pipeline**: Automatic deployments on code pushes.

3. **Cutover to Production**

   - Once testing is successful, update DNS records to point to the production domain.
   - Monitor the application closely for any issues post-deployment.

---

### Notes and Corrections

- **SQLite Usage Correction**:

  - Recognized that treating SQLite like PostgreSQL was unnecessary.
  - Removed the separate droplet for SQLite; it's now embedded within the application container.
  - Ensured data persistence using Docker volumes.

- **Security Considerations**:

  - Avoided hardcoding sensitive information in code.
  - Used GitHub Secrets and Terraform variables for managing tokens and keys.
  - Followed best practices for SSH and sudo privileges in cloud-init scripts.

- **Optimizations**:

  - Simplified the Docker Compose file by removing unnecessary services.
  - Disabled Traefik's dashboard in production for security.

**Comment by loftwah** [comment]
### **Comprehensive Deployment Plan with Checkpoints and Expected Results**

#### **Overview**

The goal is to transition your infrastructure to a fully automated, zero-downtime deployment pipeline using Terraform, Docker, Traefik, GitHub Actions, and a separate host for your SQLite database. We'll set up a test environment using a separate domain to validate everything before replacing your production setup.

### **Step-by-Step Plan**

- - -

### **Step 1: Automate Infrastructure with Terraform**

**Objective**: Use Terraform to provision DigitalOcean droplets for both the application and the database, automate Docker installation, and set up basic networking.

#### **1.1 Prepare Terraform Configuration**

**Instructions**:

1. **Install Terraform**: Ensure you have Terraform installed locally.

2. **Create a Terraform configuration directory**: Set up a new directory for your Terraform configuration files. Inside this directory, create a main configuration file, `main.tf`.

3. **Define Provider and Variables**:

   ```hcl
   # main.tf
   terraform {
     required_providers {
       digitalocean = {
         source  = "digitalocean/digitalocean"
         version = "~> 2.0"
       }
     }
   }

   provider "digitalocean" {
     token = var.do_token
   }

   variable "do_token" {
     description = "DigitalOcean API token"
   }

   variable "ssh_key_id" {
     description = "SSH key ID for DigitalOcean"
     default     = "your_ssh_key_id"
   }

   variable "region" {
     description = "DigitalOcean region"
     default     = "syd1"
   }
   ```

4. **Define Resources for Droplets**:

   ```hcl
   # Droplet for Application
   resource "digitalocean_droplet" "app" {
     name   = "rails-app"
     region = var.region
     size   = "s-2vcpu-4gb"
     image  = "ubuntu-22-04-x64"
     ssh_keys = [var.ssh_key_id]
     user_data = file("cloud-init-app.sh")
   }

   # Droplet for SQLite Database
   resource "digitalocean_droplet" "db" {
     name   = "sqlite-db"
     region = var.region
     size   = "s-1vcpu-2gb"
     image  = "ubuntu-22-04-x64"
     ssh_keys = [var.ssh_key_id]
     user_data = file("cloud-init-db.sh")
   }

   output "app_droplet_ip" {
     value       = digitalocean_droplet.app.ipv4_address
     description = "IP address of the application droplet"
   }

   output "db_droplet_ip" {
     value       = digitalocean_droplet.db.ipv4_address
     description = "IP address of the database droplet"
   }
   ```

5. **Create Cloud-init Scripts for Droplet Setup**:

   **cloud-init-app.sh**:

   ```bash
   #!/bin/bash
   apt-get update -y
   curl -fsSL https://get.docker.com | sh
   ```

   **cloud-init-db.sh**:

   ```
   bash
   Copy code
   #!/bin/bash
   apt-get update -y
   curl -fsSL https://get.docker.com | sh
   ```

**Checkpoints**:

* **Terraform Initialization**: Run `terraform init` to initialize your working directory.
* **Plan Review**: Run `terraform plan` to ensure the configuration is correct and review the changes.

**Expected Result**: Terraform should show a plan to create two droplets (one for the app, one for the database) with Docker installed. No changes should be applied yet.

**Apply Changes**: Run `terraform apply -auto-approve` to create the resources.

**Checkpoint**:

* **Droplets Created**: Verify the droplets are created in your DigitalOcean dashboard.
* **SSH Access**: Ensure you can SSH into both droplets using your SSH key.

**Expected Result**: Two droplets should be up and running, accessible via SSH, and have Docker installed.

- - -

### **Step 2: Configure Docker Compose and Traefik**

**Objective**: Set up Docker Compose to manage application services and Traefik as a reverse proxy for dynamic routing and SSL/TLS termination.

#### **2.1 Create Docker Compose Configuration**

**Instructions**:

1. **Create Docker Compose File for Application**: On the application droplet, create a `docker-compose.yml` file.

   **docker-compose.yml**:

   ```yaml
   services:
     traefik:
       image: traefik:v2.10
       command:
         - "--api.dashboard=false"
         - "--providers.docker=true"
         - "--entrypoints.web.address=:80"
         - "--entrypoints.websecure.address=:443"
         - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
         - "--certificatesresolvers.myresolver.acme.email=your-email@example.com"
         - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
       ports:
         - "80:80"
         - "443:443"
       volumes:
         - "/var/run/docker.sock:/var/run/docker.sock:ro"
         - "./letsencrypt:/letsencrypt"

     app:
       image: ghcr.io/loftwah/linkarooie:latest
       deploy:
         update_config:
           parallelism: 1
           delay: 10s
           order: start-first
       labels:
         - "traefik.enable=true"
         - "traefik.http.routers.app.rule=Host(`app.example.com`)"
         - "traefik.http.routers.app.entrypoints=web,websecure"
         - "traefik.http.routers.app.tls=true"
         - "traefik.http.routers.app.tls.certresolver=myresolver"
         - "traefik.http.services.app.loadbalancer.server.port=3000"
       env_file:
         - .env
       environment:
         - RAILS_ENV=production
         - REDIS_URL=redis://redis:6379/0
       volumes:
         - ./storage:/rails/storage
       depends_on:
         - redis

     redis:
       image: redis:6-alpine
       volumes:
         - redis_data:/data

     sidekiq:
       image: ghcr.io/loftwah/linkarooie:latest
       command: bundle exec sidekiq
       deploy:
         update_config:
           parallelism: 1
           delay: 10s
           order: start-first
       labels:
         - "traefik.enable=true"
         - "traefik.http.routers.sidekiq.rule=Host(`sidekiq.example.com`)"
         - "traefik.http.routers.sidekiq.entrypoints=web,websecure"
         - "traefik.http.routers.sidekiq.tls=true"
         - "traefik.http.routers.sidekiq.tls.certresolver=myresolver"
         - "traefik.http.services.sidekiq.loadbalancer.server.port=3000"
       env_file:
         - .env
       environment:
         - RAILS_ENV=production
         - REDIS_URL=redis://redis:6379/0
       volumes:
         - ./storage:/rails/storage
       depends_on:
         - redis

   volumes:
     redis_data:
   ```

2. **Test Docker Compose Setup**: Run `docker-compose up -d` on the application droplet to start all services.

**Checkpoints**:

* **Services Up and Running**: Verify all containers are running with `docker ps`.
* **Traefik Dashboard Disabled**: Ensure the Traefik dashboard is not exposed in production (`--api.dashboard=false`).

**Expected Result**: Application services should be running with Traefik handling routing and SSL termination.

#### **2.2 Set Up Docker Compose for SQLite Database**

**Instructions**:

1. **Create Docker Compose File for SQLite Database**: On the database droplet, create a `docker-compose-db.yml` file.

   **docker-compose-db.yml**:

   ```yaml
   services:
     sqlite:
       image: nouchka/sqlite3
       volumes:
         - ./data:/data
       ports:
         - "5432:5432"
   ```

2. **Test SQLite Setup**: Run `docker-compose -f docker-compose-db.yml up -d` on the database droplet.

**Checkpoints**:

* **SQLite Service Running**: Verify the SQLite container is running with `docker ps`.

**Expected Result**: SQLite database should be running in a separate Docker container.

- - -

### **Step 3: Set Up CI/CD with GitHub Actions**

**Objective**: Automate the build, test, and deployment process using GitHub Actions.

#### **3.1 Create GitHub Actions Workflow**

**Instructions**:

1. **Create GitHub Actions Workflow File**: In your repository, create `.github/workflows/deploy.yml`.

   **deploy.yml**:

   ```yaml
   name: CI/CD Pipeline

   on:
     push:
       branches:
         - main

   jobs:
     build:
       runs-on: ubuntu-latest

       steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1

       - name: Login to GitHub Container Registry
         uses: docker/login-action@v1
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}

       - name: Build and push Docker image
         run: |
           docker buildx build --platform linux/amd64 -t ghcr.io/loftwah/linkarooie:latest --push .

     deploy:
       runs-on: ubuntu-latest
       needs: build

       steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v1

       - name: Terraform Init
         run: terraform init

       - name: Terraform Apply
         run: terraform apply -auto-approve
   ```

2. **Commit and Push Workflow**: Commit your changes and push them to the main branch.

**Checkpoints**:

* **Workflow Triggers on Push**: Ensure the GitHub Actions workflow triggers and runs on push to the main branch.
* **Build and Deploy**: Verify that Docker images are built and pushed to the registry, and Terraform commands are executed.

**Expected Result**: The workflow should automatically build and deploy your application without manual intervention.

- - -

### **Step 4: Automate DNS Management with Cloudflare**

**Objective**: Use Cloudflare API to automate DNS updates during deployments.

#### **4.1 Update Terraform Configuration for Cloudflare Integration**

**Instructions**:

1. **Install Cloudflare Provider**: Add the Cloudflare provider to your Terraform configuration.

   **main.tf**:

   ```hcl
   provider "cloudflare" {
     email   = var.cloudflare_email
     api_key = var.cloudflare_api_key
   }

   resource "cloudflare_record" "app" {
     zone_id = var.cloudflare_zone_id
     name    = "app.example.com"
     value   = digitalocean_droplet.app.ipv4_address
     type    = "A"
     ttl     = 1
     proxied = false
   }

   variable "cloudflare_email" {}
   variable "cloudflare_api_key" {}
   variable "cloudflare_zone_id" {}
   ```

2. **Apply Terraform Changes**: Run `terraform apply -auto-approve` to update DNS records.

**Checkpoints**:

* **DNS Records Updated**: Verify DNS records in the Cloudflare dashboard.
* **Correct Domain Resolution**: Ensure domains resolve to the correct IP addresses.

**Expected Result**: DNS records should automatically update to point to the correct environment.

- - -

### **Final Validation and Cutover**

**Testing on a Separate Domain**:

1. **Set Up Test Environment**: Use a separate domain or subdomain (e.g., `test.example.com`) to test the new setup end-to-end.
2. **Validate All Components**: Ensure droplets, services, Traefik routing, SSL, database connectivity, and CI/CD pipeline all function as expected.
3. **Simulate Load and Failures**: Test rolling updates and failover scenarios to ensure zero downtime.
4. **Cutover to Production**: Once validated, modify the DNS records for your main domain to point to the new setup.

**Expected Result**: All components should function smoothly on the test domain before migrating to the production domain.

### **Conclusion**

This step-by-step guide provides a comprehensive path from your current setup to a fully automated, zero-downtime deployment pipeline. By testing on a separate domain and validating each component, you minimize risks and ensure a smooth transition.

**Comment by loftwah** [comment]
### **Refined Caveats with Examples**

When using the `cloud-init` configuration in your Terraform setup with `app.yml` and `db.yml` files, consider the following to avoid potential issues:

#### **1. Correctly Reference External Cloud-Init Files**

Ensure your Terraform configuration accurately references your external `cloud-init` files to automate droplet provisioning and setup.

**Example Terraform Configuration**:

```hcl
resource "digitalocean_droplet" "app" {
  name      = "rails-app"
  region    = var.region
  size      = "s-2vcpu-4gb"
  image     = "ubuntu-22-04-x64"
  ssh_keys  = [var.ssh_key_id]
  user_data = file("app.yml")  # Correctly referencing the external cloud-init file
}

resource "digitalocean_droplet" "db" {
  name      = "sqlite-db"
  region    = var.region
  size      = "s-1vcpu-2gb"
  image     = "ubuntu-22-04-x64"
  ssh_keys  = [var.ssh_key_id]
  user_data = file("db.yml")  # Correctly referencing the external cloud-init file
}
```

**Key Point**: Make sure the file paths (`app.yml` and `db.yml`) are accurate and accessible.

#### **2. Test Cloud-Init Scripts in a Non-Production Environment**

Before deploying to production, test your `cloud-init` scripts to ensure they perform as expected:

**Example Testing Steps**:

* **Provision a Test Droplet**: Use DigitalOcean’s console or Terraform with a minimal setup to create a test droplet.

* **Apply Cloud-Init Configuration**: Reference your `app.yml` or `db.yml` files in the test droplet's `user_data`.

* **Verify Configuration**:

  * SSH into the droplet.
  * Check that users are created correctly.
  * Confirm Docker is installed and running (`docker --version`).

**Expected Result**: All configurations should be applied as defined in your `cloud-init` files without errors.

#### **3. Follow Security Best Practices for User Setup**

Review your `cloud-init` user configurations to follow security best practices, especially regarding SSH access and `sudo` privileges.

**Example Secure User Configuration in Cloud-Init (`app.yml`)**:

```yaml
#cloud-config
users:
  - name: rails
    gecos: Rails User
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL  # Consider removing NOPASSWD after initial setup
    groups: users, admin, docker
    lock_passwd: true  # Lock password for enhanced security
    ssh_authorized_keys:
      - ssh-rsa AAAAB3Nza... dean@deanlofts.xyz
```

**Key Point**: Minimize privileges after the initial setup is complete and ensure SSH keys are correctly managed.
